name: mucke
description: The frustration-free music player.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  audio_service: # ^0.15.0
    git: 
      url: https://github.com/ryanheise/audio_service.git
      ref: one-isolate
  audio_session: ^0.0.3
  dartz: ^0.9.1
  device_info: ^1.0.0
  equatable: ^1.1.0
  file_picker: ^2.1.4
  flutter:
    sdk: flutter
  flutter_audio_query: ^0.3.5
  flutter_mobx: ^1.1.0
  get_it: ^5.0.0
  just_audio: ^0.6.2
    # git:
    #   url: https://github.com/ryanheise/just_audio.git
    #   path: just_audio  
  logging: ^0.11.4
  mobx: ^1.1.1
  moor: ^3.0.2
  path: 
  path_provider: ^1.6.18
  provider: ^4.0.4
  reorderables: ^0.3.2
  sqlite3_flutter_libs: ^0.3.0

dev_dependencies:
  build_runner: 1.10.11
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  mockito: ^4.1.1
  moor_generator: ^3.4.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
