# This is a basic workflow to help you get started with Actions

name: Validate metadata

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Validate Fastlane Supply Metadata
      # You may pin to the exact commit or the version.
      # uses: ashutoshgngwr/validate-fastlane-supply-metadata@d03bc88bf15d7c2ef8682fa057afbf2e4bc85fb4
      uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
      with:
        # Path of the Fastlane Android directory
        fastlaneDir: ./metadata
        # Throw error if a locale isn't recognised by Google Play Store
        usePlayStoreLocales: false

